### ISSUE TITLE
CSA Week 0 hacks

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/fastpages_test#2]
## Fastpages
- [Running on Github](https://xiaoa0.github.io/fastpages_test/)
- [HTML page in _posts](https://xiaoa0.github.io/fastpages_test/hello)
- [Python page in _notebooks](https://xiaoa0.github.io/fastpages_test/2022/07/28/pythonhello.html)
- [Java page in _notebooks](https://xiaoa0.github.io/fastpages_test/2022/07/21/javahello.html)
- [Commit history](https://github.com/xiaoa0/fastpages_test/graphs/contributors)
- ![In VSC](https://raw.githubusercontent.com/xiaoa0/fastpages_test/master/image.png)

## Java
- ![Running on localhost](https://raw.githubusercontent.com/xiaoa0/java_sample/master/image.png)
- [Test commit](https://github.com/xiaoa0/java_sample/commit/0c3a1b40c551805d9b39f32a64ffaced4d16c0e4)

**Comment by jm1021** [comment]
Very nice job.  Excellent way of presenting requirements.  You are great at managing and presenting information and capturing detail.
