### ISSUE TITLE
CSP Fastpages hacks

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/fastpages_test#3]
## Fastpages
- [Running on Github](https://xiaoa0.github.io/fastpages_test/)
- [HTML page in _posts](https://xiaoa0.github.io/fastpages_test/hello)
- [Python page in _notebooks](https://xiaoa0.github.io/fastpages_test/2022/07/28/pythonhello.html)
- [Commit history](https://github.com/xiaoa0/fastpages_test/graphs/contributors)
- ![In VSC](https://raw.githubusercontent.com/xiaoa0/fastpages_test/master/image.png)

**Comment by jm1021** [comment]
Looks like you got stuff working well.  Great job.  It would be nice to see some personalization on index.html before next time.
