### ISSUE TITLE
Week 1: Innovation (2.7/3)

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/fastpages_test#4]
### Pair score: 2.7/3
Grading score: 2.7/3

- Code.org
![](https://raw.githubusercontent.com/xiaoa0/fastpages_test/master/images/Screenshot%202022-08-29%20at%2002-28-33%20Object-Oriented%20Programming%20('22-'23)%20-%20Code.org.png)
- [IJava to document primitives](https://xiaoa0.github.io/fastpages_test/collegeboard/2022/08/23/week1hacks.html#Calculator-function)
- [Bash for machine setup](https://xiaoa0.github.io/fastpages_test/jupyter/2022/08/28/bashcheck.html)
![](https://raw.githubusercontent.com/xiaoa0/fastpages_test/master/images/Screenshot%202022-08-29%20003836.png)
![](https://raw.githubusercontent.com/xiaoa0/fastpages_test/master/images/Screenshot%202022-08-29%20093649.png)
- [Fastpages](https://xiaoa0.github.io/fastpages_test/) organization
- [x] [Tags](https://xiaoa0.github.io/fastpages_test/categories/)
- [x] [Images with markdown](https://xiaoa0.github.io/fastpages_test/markdown/2022/08/29/imagepost.html)
- [x] [Documentation hacks](https://xiaoa0.github.io/fastpages_test/jupyter/2022/08/29/notesplanning.html)

**Comment by SlimeyTurtles** [comment]
Full credit 😎🤘🤘
