### ISSUE TITLE
Week 2: Team Innovation

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/fastpages_test#5]
### Teacher grading: /3

- Code.org work and [notes](https://xiaoa0.github.io/fastpages_test/jupyter/2022/09/05/oopcodelearnings.html) ![](https://raw.githubusercontent.com/xiaoa0/fastpages_test/master/images/Screenshot%202022-09-05%20at%2016-46-44%20Object-Oriented%20Programming%20('22-'23)%20-%20Code.org.png) 
- [Java terminal](https://xiaoa0.github.io/fastpages_test/jupyter/2022/09/02/javaterminal.html)
- [Group project brainstorming](https://github.com/xiaoa0/springportfolio/issues/2)

**Comment by abac1st** [comment]
2.7/3 Terminal work uses concepts from Code.org, notes included and complete

**Comment by SlimeyTurtles** [comment]
2.7 bec she did all the work :ok_hand:
