### ISSUE TITLE
Week 3: Backend Development

### ISSUE THREAD

**Issue by xiaoa0** [xiaoa0/fastpages_test#6]
- [Focus/mindset hack on Fastpages](https://xiaoa0.github.io/fastpages_test/jupyter/2022/09/11/psychnotes.html)
- [Boolean expressions](https://xiaoa0.github.io/fastpages_test/jupyter/2022/09/09/boolean.html)
- Deployment

**Comment by SlimeyTurtles** [comment]
2.5/3  no deployment
